### PR TITLE
Heatmap notebook

### PR DESCRIPTION
**Pull request by ariguiba**
Added a Notebook about visualizing data in the 3D Space. 

The notebook introduces 3 representations: 
- Heatmaps
- 3D graphs
- Contours

The user gets to set the z value using a PlutoUI slider and see how which points have this value in all the different representations. 

Moreover, there are different testing functions available to play around with.

### CODE REVIEW

**Comment by ariguiba** [comment]
Hello, this notebook is also done and ready for review :+1:

**Comment by fonsp** [comment]
Awesome, I'm merging it! That means it will be included in the next pluto release 🎉

One thing to improve is the `@lift` and Observable: it's a small chunk of hard-to read "magical" code with no explanation. You could add a comment to explain what/why/how, or even better is to find a way to avoid it :)

Anyway this is awesome!!

**Comment by fonsp** [comment]
Oh for the frontmatter that I added, I just copied author: JuliaPluto, license: Unlicense from the other notebooks. We could also write you as the author, or pick another license! What do you think? @behinger did you already think about the license?

**Comment by behinger** [comment]
Unlicense is fine. Author wise we already had a discussion, but no conclusion I think. my gut feeling as a scientist is to put the names there, but maybe that is just my neoliberal roots that are hard to shake ;-)

**Comment by ariguiba** [comment]
> Awesome, I'm merging it! That means it will be included in the next pluto release tada
> 
> One thing to improve is the `@lift` and Observable: it's a small chunk of hard-to read "magical" code with no explanation. You could add a comment to explain what/why/how, or even better is to find a way to avoid it :)
> 
> Anyway this is awesome!!

Hello! Thanks for the small changes it looks even better now. Yes I can add some more comments to the code. My idea with this notebook was really to put forward the visualization and all the code is hidden anyways, so I didn't put much focus on that but you're right it's always good to comment the code, for any interested people :) 

Should I commit directly to the main branch or open this pull request again?

**Comment by ariguiba** [comment]
> Unlicense is fine. Author wise we already had a discussion, but no conclusion I think. my gut feeling as a scientist is to put the names there, but maybe that is just my neoliberal roots that are hard to shake ;-) - that is, I'm fine with JuliaPluto, but the exposure might be relevant to Boshra

For me, I don't have a problem with JuliaPluto as the author, since I would love it if in the future the notebooks can be expanded or improved by other developers BUT as long as I am also named under the Pluto contributors of course haha :) (Somewhere in the website or here in github is enough for me)

**Comment by fonsp** [comment]
You can commit directly or a PR, up to you!

Actually, I think it's nicer to write your name as the author! It's a more visible way to credit you, and the goal is to show off notebooks from many authors, not just "official" notebooks. How does that sound?

If you like, you could upload a picture/drawing/plain color/heatmap as your github profile picture and it will show as the tiny author picture in the menu of featured notebooks ⭐️

**Comment by ariguiba** [comment]
> You can commit directly or a PR, up to you!
> 
> Actually, I think it's nicer to write your name as the author! It's a more visible way to credit you, and the goal is to show off notebooks from many authors, not just "official" notebooks. How does that sound?
> 
> If you like, you could upload a picture/drawing/plain color/heatmap as your github profile picture and it will show as the tiny author picture in the menu of featured notebooks star

That sounds great, yes let's do that! :+1:

**Pull request merged**
