### PR TITLE
Moon Emoji Featured Notebook

### PR DESCRIPTION
**Pull request by behinger**
the quickest featured notebook in the wild west 🤠

### CODE REVIEW

**Comment by behinger** [comment]
maybe someone can have a look? It is just 4-5 lines of code

**Comment by declann** [comment]
It looks cool to me.

I don't have a secure environment for running notebooks ATM so I be super nervous about code/dependencies. Here I copied L1-43 after reviewing it and I let Pluto do it's thing with that, and comparing what my Pluto generates, everything is fine (some minor version differences in dependencies).

The only feedback I can think up is if the Authors comment necessary whenever frontmatter includes them? Maybe Pluto should surface the notebook authors better instead.

I like this as a simple notebook example, however I amn't the curator and now that I look for guidelines, I notice the readme comment on New Submissions advising to "Hold On" without an invite:

https://github.com/JuliaPluto/featured#new-submissions

Anyways, quick notebook but fun and concise too!

**Comment by fonsp** [comment]
Awesome!! More notebooks like this one please! 💛

**Comment by fonsp** [comment]
Btw in the future, you can list multiple authors with https://github.com/fonsp/Pluto.jl/pull/2650 ! Right now only the first author will be shown in this screen

image

but we could make that better :)


Also remember that `image` is the thumbnail of the notebook itself, and `author_image` (or the `image` field of an `author` after https://github.com/fonsp/Pluto.jl/pull/2650) controls the little profile picture.

**Comment by behinger** [comment]
Sounds great! Thanks for creating multiple authors :) 
---

for some reason "moon" doesnt show up on the website?

But exists here: https://featured.plutojl.org/basic/moon.html

**Pull request merged**
